INSERT INTO products
(name, description, price, stock_quantity, keywords, status, version, created_at, updated_at)
VALUES ('iPhone 15 Pro', '苹果最新款智能手机，搭载A17 Pro芯片', 7999.00, 50, '苹果 iPhone 手机 智能手机 A17', 'active',
        1, NOW(), NOW()),
       ('MacBook Air M2', '苹果超薄笔记本电脑，搭载M2芯片', 8999.00, 30, '苹果 MacBook 笔记本 电脑 M2', 'active', 1,
        NOW(), NOW()),
       ('iPad Pro 12.9英寸', '苹果专业级平板电脑，支持Apple Pencil', 8599.00, 25, '苹果 iPad 平板 电脑 Pro', 'active', 1,
        NOW(), NOW()),
       ('AirPods Pro 2', '苹果无线耳机，主动降噪功能', 1899.00, 100, '苹果 AirPods 耳机 无线 降噪', 'active', 1, NOW(),
        NOW()),
       ('Apple Watch Series 9', '苹果智能手表，健康监测功能', 2999.00, 80, '苹果 Apple Watch 智能手表 健康', 'active', 1,
        NOW(), NOW()),
       ('小米13 Pro', '小米旗舰手机，徕卡摄影系统', 4999.00, 60, '小米 手机 智能手机 徕卡 拍照', 'active', 1, NOW(),
        NOW()),
       ('华为P60 Pro', '华为旗舰手机，超级变焦摄影', 6988.00, 45, '华为 手机 智能手机 拍照 变焦', 'active', 1, NOW(),
        NOW()),
       ('Samsung Galaxy S23 Ultra', '三星旗舰手机，S Pen支持', 9699.00, 35, '三星 Samsung 手机 智能手机 S Pen', 'active',
        1, NOW(), NOW()),
       ('Dell XPS 13', 'Dell高端超极本，轻薄便携', 7999.00, 20, 'Dell 笔记本 电脑 轻薄 便携', 'active', 1, NOW(), NOW()),
       ('联想ThinkPad X1 Carbon', '联想商务笔记本，经典黑色设计', 12999.00, 15, '联想 ThinkPad 笔记本 商务 电脑',
        'active', 1, NOW(), NOW()),
       ('Sony WH-1000XM5', '索尼无线降噪耳机，LDAC高音质', 2399.00, 70, '索尼 Sony 耳机 无线 降噪 LDAC', 'active', 1,
        NOW(), NOW()),
       ('Nintendo Switch OLED', '任天堂游戏机，OLED屏幕版本', 2599.00, 40, '任天堂 Nintendo Switch 游戏机 OLED',
        'active', 1, NOW(), NOW()),
       ('Kindle Paperwhite', '亚马逊电子书阅读器，护眼屏幕', 998.00, 90, '亚马逊 Kindle 电子书 阅读器', 'active', 1,
        NOW(), NOW()),
       ('Bose QuietComfort 45', 'Bose无线降噪耳机，舒适佩戴', 2498.00, 55, 'Bose 耳机 无线 降噪 舒适', 'active', 1,
        NOW(), NOW()),
       ('GoPro Hero 11', 'GoPro运动相机，4K录制', 3498.00, 30, 'GoPro 运动相机 4K 录制 防水', 'active', 1, NOW(), NOW()),
       ('测试缺货商品', '这是一个测试用的缺货商品', 99.00, 0, '测试 缺货', 'out_of_stock', 1, NOW(), NOW());