# Generated by Django 5.2 on 2025-06-27 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order_no",
                    models.CharField(max_length=50, unique=True, verbose_name="订单号"),
                ),
                ("user_id", models.PositiveIntegerField(verbose_name="用户ID")),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="总金额"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待处理"),
                            ("completed", "已完成"),
                            ("partial", "部分成功"),
                            ("failed", "失败"),
                            ("cancelled", "已取消"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "orders",
                "indexes": [
                    models.Index(fields=["order_no"], name="orders_order_n_a26108_idx"),
                    models.Index(fields=["user_id"], name="orders_user_id_4e08b8_idx"),
                    models.Index(fields=["status"], name="orders_status_762191_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="商品名称")),
                ("description", models.TextField(blank=True, verbose_name="商品描述")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="价格"
                    ),
                ),
                (
                    "stock_quantity",
                    models.PositiveIntegerField(default=0, verbose_name="库存数量"),
                ),
                (
                    "keywords",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="搜索关键词"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "在售"),
                            ("inactive", "下架"),
                            ("out_of_stock", "缺货"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "version",
                    models.PositiveIntegerField(default=1, verbose_name="版本号"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "products",
                "indexes": [
                    models.Index(fields=["name"], name="products_name_6f9890_idx"),
                    models.Index(fields=["status"], name="products_status_a30e64_idx"),
                    models.Index(
                        fields=["keywords"], name="products_keyword_c83189_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(verbose_name="数量")),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="单价"
                    ),
                ),
                (
                    "total_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="小计"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待处理"),
                            ("success", "成功"),
                            ("failed", "失败"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="错误信息"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="comerge.order",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="comerge.product",
                    ),
                ),
            ],
            options={
                "db_table": "order_items",
                "indexes": [
                    models.Index(
                        fields=["order"], name="order_items_order_i_26ad88_idx"
                    ),
                    models.Index(
                        fields=["product"], name="order_items_product_a53db1_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="StockLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "change_type",
                    models.CharField(
                        choices=[
                            ("decrease", "减少"),
                            ("increase", "增加"),
                            ("adjust", "调整"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "quantity_before",
                    models.PositiveIntegerField(verbose_name="变更前库存"),
                ),
                (
                    "quantity_after",
                    models.PositiveIntegerField(verbose_name="变更后库存"),
                ),
                ("change_quantity", models.IntegerField(verbose_name="变更数量")),
                (
                    "reason",
                    models.CharField(blank=True, max_length=255, verbose_name="原因"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="comerge.order",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="comerge.product",
                    ),
                ),
            ],
            options={
                "db_table": "stock_logs",
                "indexes": [
                    models.Index(
                        fields=["product"], name="stock_logs_product_b77dc9_idx"
                    ),
                    models.Index(
                        fields=["order"], name="stock_logs_order_i_9ae034_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="stock_logs_created_f4e015_idx"
                    ),
                ],
            },
        ),
    ]
